version: "3.8"

services:
  db:
    container_name: postgres_infoSistemasApi
    image: postgres:latest
    volumes:
      - db_data_info:/postgres
    restart: always
    env_file:
      - ./.db.env
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    container_name: infoSistemasApi
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always
    env_file:
      - ./.env
    networks:
      - backend

volumes:
  db_data_info: {}
networks:
  backend:
    driver: bridge
